version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/src/enclave-agent"
    schedule:
      interval: daily
    open-pull-requests-limit: 1
    allow:
      - dependency-type: direct

  - package-ecosystem: "cargo"
    directory: "/src/runtime-boot/init"
    schedule:
      interval: daily
    open-pull-requests-limit: 1
    allow:
      - dependency-type: direct

  # Dependencies listed in go.mod
  - package-ecosystem: "gomod"
    directory: "/src/shim" # Location of shim's go.mod
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "github.com/containerd/containerd"
      - dependency-name: "github.com/containerd/ttrpc"
        update-types: ["version-update:semver-minor"]

  # Check updates to action versions in .github/workflows
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      # Check for updates to GitHub Actions every weekday
      interval: "daily"
