linters:
  enable:
    - structcheck
    - varcheck
    - staticcheck
    - unconvert
    - goerr113
    - gofmt
    - goimports
    - revive
    - ineffassign
    - vet
    - unused
    - misspell
  disable:
    - errcheck

run:
  timeout: 4m
  skip-dirs:
    - bin
