name: ci-test
run-name: test runtimeclass 
on: 
  push:
     branches: [ "main" ] 
jobs: 
  runtime-class:
    runs-on: self-hosted
    steps: 
      - uses: actions/checkout@v3
      
      - name: uninstall operator
        run: |
          ./.github/workflows/runtimeclass_ci.sh uninstall_coco_operator
      
      - name: step 5
        run: echo "finish"
      
    
  
