name: ci-test
run-name: test runtimeclass 
on: push
jobs: 
  runtime-class:
    runs-on: self-hosted
    steps: 
      - name: install operator
        run: |
          ./.github/workflows/runtimeclass_ci.sh install_coco_operator
      - name: install enclave-cc
        run: |
          ./.github/workflows/runtimeclass_ci.sh install_enclave_cc_runtimeclass
      - name: uninstall enclave-cc 
        run: |
          ./.github/workflows/runtimeclass_ci.sh uninstall_enclave_cc_runtimeclass
      - name: install operator
        run: |
          ./.github/workflows/runtimeclass_ci.sh uninstall_coco_operator
      - name: step 5
        run: echo "finish"
      
    
  
