name: generate-payload
run-name: test generate payload
on: push

jobs:
  build_payload_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout latest source code
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Login to Docker Container Registry
        uses: docker/login-action@v2
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USR_HLC }}
          password: ${{ secrets.QUAY_PWD_HLC }}

      - name: echo secrets
        run: "echo quay_usr_hlc: ${{ secrets.QUAY_USR_HLC }}"

      - name: build and push payload
        run: ./tools/packaging/build/build_payload.sh
        env:
            SGX_MODE: HW
            CI: yes
            PUSH: yes
