name: hlc-test
run-name: test-secrets
on: push
jobs:
  output-secret-env-vars:
    runs-on: ubuntu-latest
    steps:
      - name: step 1
        run: echo usr $QUAY_USR_HLC
      - name: step 2
        run: echo nonexist $ABC
      
