name: Publish the Enclave CC release
on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  build-asset:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - sgx_mode: SIM
            kbc: sample-kbc
          - sgx_mode: HW
            kbc: cc-kbc
    steps:
      - name: Login to quay.io
        uses: docker/login-action@v2
        with:
          registry: quay.io
          username: ${{ secrets.COCO_QUAY_DEPLOYER_USERNAME }}
          password: ${{ secrets.COCO_QUAY_DEPLOYER_PASSWORD }}

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # This is needed in order to keep the commit ids history
      - name: Build Enclave CC Payload using SGX_MODE=${{ matrix.sgx_mode }} KBC=${{ matrix.kbc }}
        run: |
          ./tools/packaging/build/build_payload.sh 
        env:
          SGX_MODE: ${{ matrix.sgx_mode }}
          KBC: ${{ matrix.kbc }}
          CI: no
          PUSH: yes
