name: CI tests

on: 
  push:
    branches: [ "main" ]

  pull_request:
    branches: [ "main" ]

jobs: 
  CI-tests:
    runs-on: self-hosted
    steps: 

      - name: Checkout latest enclave-cc source code
        if: ${{ github.event_name == 'push' }}
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Checkout PR source code
        if: ${{ github.event_name == 'pull_request' }}
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
                
      - name: Install CoCo operator
        run: ./ci/ci_tests.sh install_coco_operator

      - name: Install Enclave-CC runtimeclass payload
        run: ./ci/ci_tests.sh install_enclave_cc_runtimeclass

      - name: Pull and run a workload image signed by cosign
        run: ./ci/ci_tests.sh apply_eaa_cosign_encryped_hello_world_workload

      - name: delete workload pod
        run: |
          ./ci/ci_tests.sh delete_eaa_cosign_encrypted_hello_world_workload
          sleep 10
        
      - name: Uninstall Enclave-CC runtimeclass payload 
        run: ./ci/ci_tests.sh uninstall_enclave_cc_runtimeclass

      - name: Uninstall CoCo operator
        run: ./ci/ci_tests.sh uninstall_coco_operator 
     