name: CI tests
# run-name:   // give a dynamic name, or leave it empty
on: 
  push:
     branches: [ "main" ] 

jobs: 
  CI-tests:
    runs-on: self-hosted
    steps: 
      - name: Echo current user
        run: whoami
        
#       - name: Login to Quay.io
#         uses: docker/login-action@v2
#         with:
#           registry: quay.io
#           username: ${{ secrets.QUAY_USR_HLC }}
#           password: ${{ secrets.QUAY_PWD_HLC }}

      - name: Checkout latest enclave-cc source code
        uses: actions/checkout@v3
        with:
          ref: main
                
      - name: Install CoCo operator
        run: ./ci/ci_tests.sh install_coco_operator

      # - name: Install Enclave-CC runtimeclass payload
      #   run: ./ci/ci_tests.sh install_enclave_cc_runtimeclass

      # - name: Pull and run a workload image signed by cosign
      #   run: ./ci/ci_tests.sh apply_eaa_cosign_encryped_hello_world_workload

      # - name: delete workload
      #   run: ./ci/ci_tests.sh delete_eaa_cosign_encrypted_hello_world_workload
        
      # - name: Uninstall Enclave-CC runtimeclass payload 
      #   run: ./ci/ci_tests.sh uninstall_enclave_cc_runtimeclass

      # - name: Uninstall CoCo operator
      #   run: ./ci/ci_tests.sh uninstall_coco_operator 
     
     
    
  
